// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHO9My-IUueEpL2UjQJAAIaaAiy2NbrWI',
    appId: '1:544186740113:web:1900332db855a5c0853e30',
    messagingSenderId: '544186740113',
    projectId: 'cvprojectfire',
    authDomain: 'cvprojectfire.firebaseapp.com',
    storageBucket: 'cvprojectfire.appspot.com',
    measurementId: 'G-S6SNR7L4YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDGKQoEQRau-SdXzOxOu9x-cp5x03Ki_8',
    appId: '1:544186740113:android:b95f39dda02869c4853e30',
    messagingSenderId: '544186740113',
    projectId: 'cvprojectfire',
    storageBucket: 'cvprojectfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_mmxrXILpt_IXUt_7yme25AegTxb4_6E',
    appId: '1:544186740113:ios:ca112575d926805d853e30',
    messagingSenderId: '544186740113',
    projectId: 'cvprojectfire',
    storageBucket: 'cvprojectfire.appspot.com',
    iosClientId: '544186740113-3smff7mnsp7p8920pdr4t53n49glvipc.apps.googleusercontent.com',
    iosBundleId: 'ham.com.active.cvproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_mmxrXILpt_IXUt_7yme25AegTxb4_6E',
    appId: '1:544186740113:ios:ca112575d926805d853e30',
    messagingSenderId: '544186740113',
    projectId: 'cvprojectfire',
    storageBucket: 'cvprojectfire.appspot.com',
    iosClientId: '544186740113-3smff7mnsp7p8920pdr4t53n49glvipc.apps.googleusercontent.com',
    iosBundleId: 'ham.com.active.cvproject',
  );
}
